# config.py

import numpy as np
import math

MAVLINK_DEVICE = '/dev/ttyACM0'
MAVLINK_BAUD = 115200
COMPANION_COMPUTER_ID = 10
VIO_RATE_HZ = 40.0
HEARTBEAT_RATE_HZ = 1.0
SAVE_FRAMES = True
JPG_OUTPUT_DIR = "landing_zone_output"
VIDEO_FPS = 20

# VIO and SLAM parameters
IMG_WIDTH = 640
IMG_HEIGHT = 480
HFOV_DEG = 73.0
PIXELS_PER_RAD = IMG_WIDTH / np.deg2rad(HFOV_DEG)
ROI_SCALE = 0.8
VELOCITY_DEADZONE = 0.02
IMU_FREQUENCY = 20
HEADING_OFFSET_DEG = 7.0
HEADING_OFFSET_RAD = math.radians(HEADING_OFFSET_DEG)

KEYFRAME_ALTITUDE_THRESHOLD = 2.0
KEYFRAME_DISTANCE_THRESHOLD = 0.75

TAKEOFF_ALTITUDE_M = 3.0
MAX_SAFE_SPOTS_TO_LAND = 3
SURVEY_SPEED_MPS = 0.5
SURVEY_DISTANCE_M = 10.0

# landing spot detection config
EDGE_THRESHOLD = 75 
MAX_NOISE_INTENSITY = 150.0 
UNSAFE_BOUNDARY_PCT = 0.10 
CONFIRMATION_FRAMES_REQUIRED = 8
CLEANING_KERNEL_SIZE = 11 
EDGE_CLEANING_KERNEL_SIZE = 3
REQUIRED_LANDING_SIZE_M = 1.5
DUPLICATE_SPOT_DISTANCE_M = 1.25
MIN_DETECTION_ALTITUDE_M = 2.0
HOME_EXCLUSION_RADIUS_M = 1.5
